export const list=[
    {
        id: 1,
        photo:'https://th.bing.com/th/id/OIP.v5Ux2e45Dtoc8jCJNmtalwHaEO?w=272&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
        type: "For Rent",
        location:'London',
        name:"RCE Theaters",
        price:7255,
    },
    {
        id: 2,
        photo:'https://3.bp.blogspot.com/-1byge6qgzN8/UoopoSL0oqI/AAAAAAAAe24/ZaT8D8DHHJw/s1600/Paris-Luxury-Hotel-Sofitel-passion4luxury-10.jpg',
        type: "For Rent",
        location:'London',
        name:"RCE Theaters",
        price:7255,
    },
    {
        id: 3,
        photo:'https://th.bing.com/th/id/R.2007d6dd4ca8f4b527d19c7baaefab7e?rik=rReSTBlU8EgXgg&riu=http%3a%2f%2fwww.offtoeurope.com%2fwp-content%2fuploads%2f2010%2f06%2fradisson-pool.jpg&ehk=CaUisnyP5kcZ1RoXpnFLf0ILEA5k18TKljqzIPNw9JI%3d&risl=1&pid=ImgRaw&r=0',
        type: "For Sale",
        location:'London',
        name:"RCE Theaters",
        price:7255,
    },
    {
        id: 4,
        photo:'https://th.bing.com/th/id/R.6a0111731dbab33d149f699f397281ee?rik=D3SSaKRIOvzxug&riu=http%3a%2f%2f1.bp.blogspot.com%2f-oVe3zrIYfWs%2fTvni3TW9xII%2fAAAAAAAAAd4%2fFHsKu37dNUc%2fs1600%2fPolonia%2bPalace%2bHotel%2bFront.jpg&ehk=eC0uIYVq0gpkyxG4hZCSr%2fc7zcgZvwRL1C9%2btkVI6Ps%3d&risl=&pid=ImgRaw&r=0',
        type: "For Rent",
        location:'London',
        name:"RCE Theaters",
        price:7255,
    },
    {
        id: 5,
        photo:'https://th.bing.com/th/id/R.da157e1a20f4c534641f77d68a2af094?rik=MreMizIdFusUNQ&riu=http%3a%2f%2ftravelspan.in%2fwp-content%2fuploads%2f2019%2f04%2fIndian-Hotels-Company-Limited-opens-Taj-Rishikesh-Resort-and-Spa-in-Uttarakhand.jpg&ehk=88YHTB5Ugt2Jf9LxbObknpsoIZ0XAL2T5bBzQR7nHkU%3d&risl=&pid=ImgRaw&r=0',
        type: "For Sale",
        location:'London',
        name:"RCE Theaters",
        price:7255,
    },
    {
        id: 6,
        photo:'https://a.loveholidays.com/images/holidays/spain/costa-brava/lloret-de-mar/h-top-palm-beach-hotel.jpg',
        type: "For Rent",
        location:'London',
        name:"RCE Theaters",
        price:7255,
    },
    {
        id: 7,
        photo:'https://digital.ihg.com/is/image/ihg/holiday-inn-hotel-and-suites-clearwater-beach-6477439006-4x3',
        type: " For Sale",
        location:'London',
        name:"RCE Theaters",
        price:7255,
    },
    {
        id: 8,
        photo:'https://cdn.decoist.com/wp-content/uploads/2016/12/Lavish-suite-with-a-view-of-the-Eiffel-at-Shangri-La-Hotel-Paris.jpg',
        type: "For Rent",
        location:'London',
        name:"RCE Theaters",
        price:7255,
    },
    {
        id: 9,
        photo:'https://th.bing.com/th/id/OIP.v5Ux2e45Dtoc8jCJNmtalwHaEO?w=272&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
        type: "For Sale",
        location:'London',
        name:"RCE Theaters",
        price:7255,
    },
]